### ISSUE TITLE
ModuleNotFoundError: No module named 'vim'

### ISSUE THREAD

**Issue by tiagolupepic** [craigemery/vim-autotag#34]
I've upgraded to the latest vim available on homebrew 8.2.0750 and I'm getting this error when I save a file.

```
Traceback (most recent call last):)
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/tiagolupepic/.vim/bundle/vim-autotag/plugin/autotag.py", line 16, in <module>
    import vim  # pylint: disable=import-error
```

- Catalina 10.15.14
- Python 3.8.
- Vim 8.2.0750 and 8.2.1797

To test I compiled the vim using the parameter `--HEAD` and I get the same error

My vim version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 19 2020 17:31:53)
macOS version
Included patches: 1-797
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.2_1/lib/perl5/5.30.2/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -lpython3.8 -framework CoreFoundation  -lruby.2.7
```

Running this snippet https://github.com/Homebrew/homebrew-core/blob/master/Formula/vim.rb#L69 manually from Homebrew the `import vim` works fine.

**Comment by craigemery** [comment]
You I’ve vim was built -python 
Hence the missing vim python module. 

Sorry. You need a vim built with Python 

Craig

**Comment by craigemery** [comment]
Can you just run Vim and do
pyx import vim 
?

**Comment by craigemery** [comment]
Interestingly it’s in spawn. 
So it’s the thread in multi processing

**Comment by tiagolupepic** [comment]
running with `:pyx`

`:pyx import vim, sys; print(sys.version)`
```
3.8.2 (default, Mar 11 2020, 00:29:50)
[Clang 11.0.0 (clang-1100.0.33.17)]
```

**Comment by tiagolupepic** [comment]
The problem is related to the start method from multiprocessing. In Python 3.8 they changed the default in macOS to use `spawn` instead of `fork`.

Installed Python 3.8 from Homebrew.
```
 % python3
Python 3.8.2 (default, Mar 11 2020, 00:29:50)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocessing as mp; mp.get_start_method()
'spawn'
>>>
```
Native Python 3.7 from Catalina.
```
 % /usr/bin/python3
Python 3.7.3 (default, Apr  7 2020, 14:06:47)
[Clang 11.0.3 (clang-1103.0.32.59)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocessing as mp; mp.get_start_method()
'fork'
>>>
```

**Comment by craigemery** [comment]
I thought I'd already helped someone else with 3.8 & spawn.
Look at my closed tickets.
Is your autotag plugin code up to date?

Craig

**Comment by tiagolupepic** [comment]
this one https://github.com/craigemery/vim-autotag/issues/33, right? Yep, I have the plugin updated. 
I checked the comments and the fix is related to set the executable correctly, the problem now, seems we have the correct executable but this executable continues using `spawn` instead of `fork`.

**Comment by craigemery** [comment]
Wow. OK - so I'm calling mp.Process().start() and I'm not specifying spawn or fork or anything.
So could this be a bug in Python 3.8 on macOS? I've asked over on #33 how things are.
See if we can find a difference.

**Comment by craigemery** [comment]
I've just pushed 124d4db743a632115a275cb3892bc86f17709a49.
It allows the setting of an alternative start method.
On my Mojave Mac, with Python 3.7, the choices are: fork, spawn & forkserver.
The default in 3.7 is fork. For Python 3.8 the default changed to spawn.
I did:
let g:autotagStartMethod='spawn'
And things seemed to work OK.
Certainly, things are OK in Windows 10 (the only choice is 'spawn').
If you supply a string that is not one of the allowed methods, I use None & you get the system default.

So please try 'fork' on your Catalina, Python 3.8 system.

**Comment by kitop** [comment]
i just got this again, and able to reproduce. Funny it's just after you pinged in #33 
Will try the new commit and update.

**Comment by kitop** [comment]
Setting `let g:autotagStartMethod='fork'` removed the errors for me! Thanks!
Still getting them if I set to `spawn`, so maybe worth documenting?

**Comment by craigemery** [comment]
So it looks like 'spawn' start method is less mature than we'd like even though it's now the default start method.
I can make the default change if we detect 3.8 Python & macOS?

**Comment by tiagolupepic** [comment]
I tested too and worked fine setting the `let g:autotagStartMethod='fork'` 🎉

**Comment by craigemery** [comment]
I've updated the readme, I know this is a bit more a workaround than an absolute fix, but I'm going to close this bug. ;-)
